### ISSUE TITLE
2024.1版本idea报错

### ISSUE THREAD

**Issue by D-Jancy** [starxg/mybatis-log-plugin-free#23]
日志：
```txt
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.starxg.mybatislog.action.StopAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.starxg.mybatis-log-plugin-free]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

```
其他插件也有报错差不多的日志，不知道是不是idea的问题

**Comment by Panpan021** [comment]
Hey, how did you solve the problem? Can you please share?
