### ISSUE TITLE
2024版本报错

### ISSUE THREAD

**Issue by ljjadmin-beep** [starxg/mybatis-log-plugin-free#28]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.starxg.mybatislog.action.PreviousSqlAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.starxg.mybatis-log-plugin-free]

**Comment by Panpan021** [comment]
Hey, how did you solve the problem? Can you please share?

**Comment by canotf** [comment]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.starxg.mybatislog.action.PreviousSqlAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.starxg.mybatis-log-plugin-free]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

yes，我也有这种问题，一打开idea就报错，虽然过一会自己又能用了，但是看着碍眼
